module.exports = {
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#636263",
        "on-secondary-fixed-variant": "#474647",
        "primary-fixed-dim": "#ffb94c",
        "on-secondary-fixed": "#1b1b1c",
        "on-background": "#1a1c1c",
        "on-surface": "#1a1c1c",
        "surface-container-low": "#f3f3f4",
        "surface-container": "#eeeeee",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#291800",
        "outline-variant": "#d5c4af",
        "on-tertiary-fixed-variant": "#474745",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        primary: "#815500",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-high": "#e8e8e8",
        outline: "#837563",
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "tertiary-fixed-dim": "#c8c6c3",
        "surface-tint": "#815500",
        "on-primary-fixed-variant": "#624000",
        error: "#ba1a1a",
        "secondary-fixed-dim": "#c8c6c7",
        "inverse-primary": "#ffb94c",
        "on-primary-container": "#694500",
        surface: "#f9f9f9",
        "primary-fixed": "#ffddb2",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        tertiary: "#5f5e5c",
        background: "#f9f9f9",
        "on-tertiary-container": "#4c4c4a",
        secondary: "#5f5e5f",
        "inverse-on-surface": "#f0f1f1",
        "error-container": "#ffdad6",
        "primary-container": "#f5b041",
        "on-surface-variant": "#514535",
        "secondary-fixed": "#e5e2e3",
        "inverse-surface": "#2f3131",
        "tertiary-container": "#bebdba",
        "secondary-container": "#e2dfe0",
        "tertiary-fixed": "#e4e2df",
        "on-tertiary-fixed": "#1b1c1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "max-width": "1280px",
      },
      fontFamily: {
        "headline-xl-mobile": ["Montserrat"],
        "body-md": ["Public Sans"],
        "headline-xl": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "body-lg": ["Public Sans"],
        "label-md": ["Public Sans"],
        "headline-md": ["Montserrat"],
      },
      fontSize: {
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
